// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Wikimedia.OpenApiClient.Models;
using Soenneker.Wikimedia.OpenApiClient.Page.MobileHtml.Item.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Wikimedia.OpenApiClient.Page.MobileHtml.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \page\mobile-html\{title}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithTitleItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Wikimedia.OpenApiClient.page.mobileHtml.item.item collection</summary>
        /// <param name="position">Optional page revision. Note that older revisions are not stored, so request latency with the revision would be higher.</param>
        /// <returns>A <see cref="global::Soenneker.Wikimedia.OpenApiClient.Page.MobileHtml.Item.Item.WithRevisionItemRequestBuilder"/></returns>
        public global::Soenneker.Wikimedia.OpenApiClient.Page.MobileHtml.Item.Item.WithRevisionItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("revision", position);
                return new global::Soenneker.Wikimedia.OpenApiClient.Page.MobileHtml.Item.Item.WithRevisionItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wikimedia.OpenApiClient.Page.MobileHtml.Item.WithTitleItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTitleItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/page/mobile-html/{title}{?redirect*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wikimedia.OpenApiClient.Page.MobileHtml.Item.WithTitleItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTitleItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/page/mobile-html/{title}{?redirect*}", rawUrl)
        {
        }
        /// <summary>
        /// &quot;Gets the content HTML optimized for mobile consumption for the given page. This contentis derived from Parsoid HTML (see `/page/html/{title}` endpoint).The difference to Parsoid HTML is roughly:* Some elements and attributes not needed for the reading case are removed.* LeadIntroductionTransform: The introductory paragraph is moved before an infobox.* RedLinks: Red links are flattened (=turned into span elements).* WidenImage: images that should be displayed in gallery are widened.* Section headings are slightly changed by wrapping the headings inside a div and adding  a span element inside the new div for the edit buttons.* Additional classes are added to img elements to fix issues with non-white backgrounds.  See Theme support below for instructions on how to enable that.* Pagelib CSS files needed to display the content are referenced.* LazyLoadTransform: server-side portion/prep for lazy loading of images.* CollapseTable: server-side portion/prep for collapsing tables.What&apos;s not included? What parts of the PageLibrary does a client still have to do?* Theme support: Themes can be turned on by adding a theme class to the root &lt;html&gt; tag.  Possible class names are:  * `pagelib_theme_default`  * `pagelib_theme_dark`  * `pagelib_theme_black`  * `pagelib_theme_sepia`  The pagelib JS has functionality to do that: ThemeTransform.setTheme(document, theme).* Dim images: DimImagesTransform.dim(window, enable)* PlatformTransform.classify(window) to trigger Android and iOS app specific CSS rules* LazyLoadTransformer: client side companion of LazyLoadTransform (note the extra *er*here)* FooterTransformer: seems to be more UI than content, requires I18N, tooStability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental)&quot;
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Wikimedia.OpenApiClient.Models.Problem_1">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Wikimedia.OpenApiClient.Models.Problem_1">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> GetAsync(Action<RequestConfiguration<global::Soenneker.Wikimedia.OpenApiClient.Page.MobileHtml.Item.WithTitleItemRequestBuilder.WithTitleItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> GetAsync(Action<RequestConfiguration<global::Soenneker.Wikimedia.OpenApiClient.Page.MobileHtml.Item.WithTitleItemRequestBuilder.WithTitleItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::Soenneker.Wikimedia.OpenApiClient.Models.Problem_1.CreateFromDiscriminatorValue },
                { "XXX", global::Soenneker.Wikimedia.OpenApiClient.Models.Problem_1.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &quot;Gets the content HTML optimized for mobile consumption for the given page. This contentis derived from Parsoid HTML (see `/page/html/{title}` endpoint).The difference to Parsoid HTML is roughly:* Some elements and attributes not needed for the reading case are removed.* LeadIntroductionTransform: The introductory paragraph is moved before an infobox.* RedLinks: Red links are flattened (=turned into span elements).* WidenImage: images that should be displayed in gallery are widened.* Section headings are slightly changed by wrapping the headings inside a div and adding  a span element inside the new div for the edit buttons.* Additional classes are added to img elements to fix issues with non-white backgrounds.  See Theme support below for instructions on how to enable that.* Pagelib CSS files needed to display the content are referenced.* LazyLoadTransform: server-side portion/prep for lazy loading of images.* CollapseTable: server-side portion/prep for collapsing tables.What&apos;s not included? What parts of the PageLibrary does a client still have to do?* Theme support: Themes can be turned on by adding a theme class to the root &lt;html&gt; tag.  Possible class names are:  * `pagelib_theme_default`  * `pagelib_theme_dark`  * `pagelib_theme_black`  * `pagelib_theme_sepia`  The pagelib JS has functionality to do that: ThemeTransform.setTheme(document, theme).* Dim images: DimImagesTransform.dim(window, enable)* PlatformTransform.classify(window) to trigger Android and iOS app specific CSS rules* LazyLoadTransformer: client side companion of LazyLoadTransform (note the extra *er*here)* FooterTransformer: seems to be more UI than content, requires I18N, tooStability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental)&quot;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Wikimedia.OpenApiClient.Page.MobileHtml.Item.WithTitleItemRequestBuilder.WithTitleItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Wikimedia.OpenApiClient.Page.MobileHtml.Item.WithTitleItemRequestBuilder.WithTitleItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "text/html, application/problem+json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wikimedia.OpenApiClient.Page.MobileHtml.Item.WithTitleItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Wikimedia.OpenApiClient.Page.MobileHtml.Item.WithTitleItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Wikimedia.OpenApiClient.Page.MobileHtml.Item.WithTitleItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// &quot;Gets the content HTML optimized for mobile consumption for the given page. This contentis derived from Parsoid HTML (see `/page/html/{title}` endpoint).The difference to Parsoid HTML is roughly:* Some elements and attributes not needed for the reading case are removed.* LeadIntroductionTransform: The introductory paragraph is moved before an infobox.* RedLinks: Red links are flattened (=turned into span elements).* WidenImage: images that should be displayed in gallery are widened.* Section headings are slightly changed by wrapping the headings inside a div and adding  a span element inside the new div for the edit buttons.* Additional classes are added to img elements to fix issues with non-white backgrounds.  See Theme support below for instructions on how to enable that.* Pagelib CSS files needed to display the content are referenced.* LazyLoadTransform: server-side portion/prep for lazy loading of images.* CollapseTable: server-side portion/prep for collapsing tables.What&apos;s not included? What parts of the PageLibrary does a client still have to do?* Theme support: Themes can be turned on by adding a theme class to the root &lt;html&gt; tag.  Possible class names are:  * `pagelib_theme_default`  * `pagelib_theme_dark`  * `pagelib_theme_black`  * `pagelib_theme_sepia`  The pagelib JS has functionality to do that: ThemeTransform.setTheme(document, theme).* Dim images: DimImagesTransform.dim(window, enable)* PlatformTransform.classify(window) to trigger Android and iOS app specific CSS rules* LazyLoadTransformer: client side companion of LazyLoadTransform (note the extra *er*here)* FooterTransformer: seems to be more UI than content, requires I18N, tooStability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental)&quot;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithTitleItemRequestBuilderGetQueryParameters 
        {
            /// <summary>Requests for [redirect pages](https://www.mediawiki.org/wiki/Help:Redirects) return HTTP 302 with a redirect target in `Location` header and content in the body.To get a 200 response instead, supply `false` to the `redirect` parameter.</summary>
            [QueryParameter("redirect")]
            public bool? Redirect { get; set; }
        }
    }
}
#pragma warning restore CS0618
