// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Wikimedia.OpenApiClient.Media.MathNamespace.Render.Item.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Wikimedia.OpenApiClient.Media.MathNamespace.Render.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \media\math\render\{format}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithFormatItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Wikimedia.OpenApiClient.media.math.render.item.item collection</summary>
        /// <param name="position">The hash string of the previous POST data</param>
        /// <returns>A <see cref="global::Soenneker.Wikimedia.OpenApiClient.Media.MathNamespace.Render.Item.Item.WithHashItemRequestBuilder"/></returns>
        [Obsolete("")]
        public global::Soenneker.Wikimedia.OpenApiClient.Media.MathNamespace.Render.Item.Item.WithHashItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("hash", position);
                return new global::Soenneker.Wikimedia.OpenApiClient.Media.MathNamespace.Render.Item.Item.WithHashItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wikimedia.OpenApiClient.Media.MathNamespace.Render.Item.WithFormatItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithFormatItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/media/math/render/{format}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wikimedia.OpenApiClient.Media.MathNamespace.Render.Item.WithFormatItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithFormatItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/media/math/render/{format}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
