// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Wikimedia.OpenApiClient.Data.Lists.Batch;
using Soenneker.Wikimedia.OpenApiClient.Data.Lists.Changes;
using Soenneker.Wikimedia.OpenApiClient.Data.Lists.Item;
using Soenneker.Wikimedia.OpenApiClient.Data.Lists.Pages;
using Soenneker.Wikimedia.OpenApiClient.Data.Lists.Setup;
using Soenneker.Wikimedia.OpenApiClient.Data.Lists.Teardown;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Wikimedia.OpenApiClient.Data.Lists
{
    /// <summary>
    /// Builds and executes requests for operations under \data\lists
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ListsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The batch property</summary>
        public global::Soenneker.Wikimedia.OpenApiClient.Data.Lists.Batch.BatchRequestBuilder Batch
        {
            get => new global::Soenneker.Wikimedia.OpenApiClient.Data.Lists.Batch.BatchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The changes property</summary>
        public global::Soenneker.Wikimedia.OpenApiClient.Data.Lists.Changes.ChangesRequestBuilder Changes
        {
            get => new global::Soenneker.Wikimedia.OpenApiClient.Data.Lists.Changes.ChangesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The EmptyPathSegment property</summary>
        public global::Soenneker.Wikimedia.OpenApiClient.Data.Lists.EmptyPathSegmentRequestBuilder EmptyPathSegment
        {
            get => new global::Soenneker.Wikimedia.OpenApiClient.Data.Lists.EmptyPathSegmentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The pages property</summary>
        public global::Soenneker.Wikimedia.OpenApiClient.Data.Lists.Pages.PagesRequestBuilder Pages
        {
            get => new global::Soenneker.Wikimedia.OpenApiClient.Data.Lists.Pages.PagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The setup property</summary>
        public global::Soenneker.Wikimedia.OpenApiClient.Data.Lists.Setup.SetupRequestBuilder Setup
        {
            get => new global::Soenneker.Wikimedia.OpenApiClient.Data.Lists.Setup.SetupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The teardown property</summary>
        public global::Soenneker.Wikimedia.OpenApiClient.Data.Lists.Teardown.TeardownRequestBuilder Teardown
        {
            get => new global::Soenneker.Wikimedia.OpenApiClient.Data.Lists.Teardown.TeardownRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Wikimedia.OpenApiClient.data.lists.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Wikimedia.OpenApiClient.Data.Lists.Item.ListsItemRequestBuilder"/></returns>
        public global::Soenneker.Wikimedia.OpenApiClient.Data.Lists.Item.ListsItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.Wikimedia.OpenApiClient.Data.Lists.Item.ListsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wikimedia.OpenApiClient.Data.Lists.ListsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ListsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/data/lists", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wikimedia.OpenApiClient.Data.Lists.ListsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ListsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/data/lists", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
