// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Wikimedia.OpenApiClient.Data.Citation;
using Soenneker.Wikimedia.OpenApiClient.Data.Css;
using Soenneker.Wikimedia.OpenApiClient.Data.I18n;
using Soenneker.Wikimedia.OpenApiClient.Data.Javascript;
using Soenneker.Wikimedia.OpenApiClient.Data.Lists;
using Soenneker.Wikimedia.OpenApiClient.Data.Recommendation;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Wikimedia.OpenApiClient.Data
{
    /// <summary>
    /// Builds and executes requests for operations under \data
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DataRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The citation property</summary>
        public global::Soenneker.Wikimedia.OpenApiClient.Data.Citation.CitationRequestBuilder Citation
        {
            get => new global::Soenneker.Wikimedia.OpenApiClient.Data.Citation.CitationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The css property</summary>
        public global::Soenneker.Wikimedia.OpenApiClient.Data.Css.CssRequestBuilder Css
        {
            get => new global::Soenneker.Wikimedia.OpenApiClient.Data.Css.CssRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The i18n property</summary>
        public global::Soenneker.Wikimedia.OpenApiClient.Data.I18n.I18nRequestBuilder I18n
        {
            get => new global::Soenneker.Wikimedia.OpenApiClient.Data.I18n.I18nRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The javascript property</summary>
        public global::Soenneker.Wikimedia.OpenApiClient.Data.Javascript.JavascriptRequestBuilder Javascript
        {
            get => new global::Soenneker.Wikimedia.OpenApiClient.Data.Javascript.JavascriptRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The lists property</summary>
        public global::Soenneker.Wikimedia.OpenApiClient.Data.Lists.ListsRequestBuilder Lists
        {
            get => new global::Soenneker.Wikimedia.OpenApiClient.Data.Lists.ListsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The recommendation property</summary>
        public global::Soenneker.Wikimedia.OpenApiClient.Data.Recommendation.RecommendationRequestBuilder Recommendation
        {
            get => new global::Soenneker.Wikimedia.OpenApiClient.Data.Recommendation.RecommendationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wikimedia.OpenApiClient.Data.DataRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DataRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/data", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wikimedia.OpenApiClient.Data.DataRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DataRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/data", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
