// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using Soenneker.Wikimedia.OpenApiClient.Data;
using Soenneker.Wikimedia.OpenApiClient.Page;
using Soenneker.Wikimedia.OpenApiClient.Transform;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Wikimedia.OpenApiClient
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WikimediaOpenApiClient : BaseRequestBuilder
    {
        /// <summary>The data property</summary>
        public global::Soenneker.Wikimedia.OpenApiClient.Data.DataRequestBuilder Data
        {
            get => new global::Soenneker.Wikimedia.OpenApiClient.Data.DataRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The page property</summary>
        public global::Soenneker.Wikimedia.OpenApiClient.Page.PageRequestBuilder Page
        {
            get => new global::Soenneker.Wikimedia.OpenApiClient.Page.PageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The transform property</summary>
        public global::Soenneker.Wikimedia.OpenApiClient.Transform.TransformRequestBuilder Transform
        {
            get => new global::Soenneker.Wikimedia.OpenApiClient.Transform.TransformRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wikimedia.OpenApiClient.WikimediaOpenApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WikimediaOpenApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
            if (string.IsNullOrEmpty(RequestAdapter.BaseUrl))
            {
                RequestAdapter.BaseUrl = "/api/rest_v1";
            }
            PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
        }
    }
}
#pragma warning restore CS0618
