// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Wikimedia.OpenApiClient.Data.Lists.Item.Entries.Batch;
using Soenneker.Wikimedia.OpenApiClient.Data.Lists.Item.Entries.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Wikimedia.OpenApiClient.Data.Lists.Item.Entries
{
    /// <summary>
    /// Builds and executes requests for operations under \data\lists\{id}\entries
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EntriesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The batch property</summary>
        public global::Soenneker.Wikimedia.OpenApiClient.Data.Lists.Item.Entries.Batch.BatchRequestBuilder Batch
        {
            get => new global::Soenneker.Wikimedia.OpenApiClient.Data.Lists.Item.Entries.Batch.BatchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The EmptyPathSegment property</summary>
        public global::Soenneker.Wikimedia.OpenApiClient.Data.Lists.Item.Entries.EmptyPathSegmentRequestBuilder EmptyPathSegment
        {
            get => new global::Soenneker.Wikimedia.OpenApiClient.Data.Lists.Item.Entries.EmptyPathSegmentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Wikimedia.OpenApiClient.data.lists.item.entries.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Wikimedia.OpenApiClient.Data.Lists.Item.Entries.Item.WithEntry_ItemRequestBuilder"/></returns>
        public global::Soenneker.Wikimedia.OpenApiClient.Data.Lists.Item.Entries.Item.WithEntry_ItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("entry_id", position);
                return new global::Soenneker.Wikimedia.OpenApiClient.Data.Lists.Item.Entries.Item.WithEntry_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wikimedia.OpenApiClient.Data.Lists.Item.Entries.EntriesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EntriesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/data/lists/{id}/entries", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wikimedia.OpenApiClient.Data.Lists.Item.Entries.EntriesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EntriesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/data/lists/{id}/entries", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
