// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Wikimedia.OpenApiClient.Data.Lists.Changes.Since.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Wikimedia.OpenApiClient.Data.Lists.Changes.Since
{
    /// <summary>
    /// Builds and executes requests for operations under \data\lists\changes\since
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SinceRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Wikimedia.OpenApiClient.data.lists.changes.since.item collection</summary>
        /// <param name="position">Cutoff date (in ISO 8601). To ensure reliable synchronization, the APImight return changes which are slightly older than the cutoff date.</param>
        /// <returns>A <see cref="global::Soenneker.Wikimedia.OpenApiClient.Data.Lists.Changes.Since.Item.WithDateItemRequestBuilder"/></returns>
        public global::Soenneker.Wikimedia.OpenApiClient.Data.Lists.Changes.Since.Item.WithDateItemRequestBuilder this[DateTimeOffset position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("date", position);
                return new global::Soenneker.Wikimedia.OpenApiClient.Data.Lists.Changes.Since.Item.WithDateItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wikimedia.OpenApiClient.Data.Lists.Changes.Since.SinceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SinceRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/data/lists/changes/since", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wikimedia.OpenApiClient.Data.Lists.Changes.Since.SinceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SinceRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/data/lists/changes/since", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
