// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Wikimedia.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ListCreateBatch : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Deprecated, will be removed. Use the full list objects instead.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Wikimedia.OpenApiClient.Models.ListCreateBatchBatchItem>? Batch { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Wikimedia.OpenApiClient.Models.ListCreateBatchBatchItem> Batch { get; set; }
#endif
        /// <summary>The lists property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Wikimedia.OpenApiClient.Models.ListRead>? Lists { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Wikimedia.OpenApiClient.Models.ListRead> Lists { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wikimedia.OpenApiClient.Models.ListCreateBatch"/> and sets the default values.
        /// </summary>
        public ListCreateBatch()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wikimedia.OpenApiClient.Models.ListCreateBatch"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Wikimedia.OpenApiClient.Models.ListCreateBatch CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Wikimedia.OpenApiClient.Models.ListCreateBatch();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "batch", n => { Batch = n.GetCollectionOfObjectValues<global::Soenneker.Wikimedia.OpenApiClient.Models.ListCreateBatchBatchItem>(global::Soenneker.Wikimedia.OpenApiClient.Models.ListCreateBatchBatchItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "lists", n => { Lists = n.GetCollectionOfObjectValues<global::Soenneker.Wikimedia.OpenApiClient.Models.ListRead>(global::Soenneker.Wikimedia.OpenApiClient.Models.ListRead.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Wikimedia.OpenApiClient.Models.ListCreateBatchBatchItem>("batch", Batch);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Wikimedia.OpenApiClient.Models.ListRead>("lists", Lists);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
