// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Wikimedia.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Media_item : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The caption property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Wikimedia.OpenApiClient.Models.Media_item_caption? Caption { get; set; }
#nullable restore
#else
        public global::Soenneker.Wikimedia.OpenApiClient.Models.Media_item_caption Caption { get; set; }
#endif
        /// <summary>reference to a Mathoid-rendered math formula image</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Wikimedia.OpenApiClient.Models.Media_item_original? Original { get; set; }
#nullable restore
#else
        public global::Soenneker.Wikimedia.OpenApiClient.Models.Media_item_original Original { get; set; }
#endif
        /// <summary>section ID in which the item is found on the page</summary>
        public int? SectionId { get; set; }
        /// <summary>whether the client should show the file in an image gallery presentation</summary>
        public bool? ShowInGallery { get; set; }
        /// <summary>The file page title</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::Soenneker.Wikimedia.OpenApiClient.Models.Media_item_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wikimedia.OpenApiClient.Models.Media_item"/> and sets the default values.
        /// </summary>
        public Media_item()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wikimedia.OpenApiClient.Models.Media_item"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Wikimedia.OpenApiClient.Models.Media_item CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Wikimedia.OpenApiClient.Models.Media_item();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "caption", n => { Caption = n.GetObjectValue<global::Soenneker.Wikimedia.OpenApiClient.Models.Media_item_caption>(global::Soenneker.Wikimedia.OpenApiClient.Models.Media_item_caption.CreateFromDiscriminatorValue); } },
                { "original", n => { Original = n.GetObjectValue<global::Soenneker.Wikimedia.OpenApiClient.Models.Media_item_original>(global::Soenneker.Wikimedia.OpenApiClient.Models.Media_item_original.CreateFromDiscriminatorValue); } },
                { "section_id", n => { SectionId = n.GetIntValue(); } },
                { "showInGallery", n => { ShowInGallery = n.GetBoolValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Wikimedia.OpenApiClient.Models.Media_item_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Wikimedia.OpenApiClient.Models.Media_item_caption>("caption", Caption);
            writer.WriteObjectValue<global::Soenneker.Wikimedia.OpenApiClient.Models.Media_item_original>("original", Original);
            writer.WriteIntValue("section_id", SectionId);
            writer.WriteBoolValue("showInGallery", ShowInGallery);
            writer.WriteStringValue("title", Title);
            writer.WriteEnumValue<global::Soenneker.Wikimedia.OpenApiClient.Models.Media_item_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
