// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Wikimedia.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum MediaItemType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "image")]
        #pragma warning disable CS1591
        Image,
        #pragma warning restore CS1591
        [EnumMember(Value = "video")]
        #pragma warning disable CS1591
        Video,
        #pragma warning restore CS1591
        [EnumMember(Value = "audio")]
        #pragma warning disable CS1591
        Audio,
        #pragma warning restore CS1591
    }
}
