// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Wikimedia.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Summary : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The coordinates of the item</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Wikimedia.OpenApiClient.Models.Summary_coordinates? Coordinates { get; set; }
#nullable restore
#else
        public global::Soenneker.Wikimedia.OpenApiClient.Models.Summary_coordinates Coordinates { get; set; }
#endif
        /// <summary>Wikidata description for the page</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The page language direction code</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Dir { get; set; }
#nullable restore
#else
        public string Dir { get; set; }
#endif
        /// <summary>&quot;The page title how it should be shown to the user.Deprecated: Use `titles.display` instead.&quot;</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Displaytitle { get; set; }
#nullable restore
#else
        public string Displaytitle { get; set; }
#endif
        /// <summary>First several sentences of an article in plain text</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Extract { get; set; }
#nullable restore
#else
        public string Extract { get; set; }
#endif
        /// <summary>First several sentences of an article in simple HTML format</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExtractHtml { get; set; }
#nullable restore
#else
        public string ExtractHtml { get; set; }
#endif
        /// <summary>The page language code</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Lang { get; set; }
#nullable restore
#else
        public string Lang { get; set; }
#endif
        /// <summary>The originalimage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Wikimedia.OpenApiClient.Models.Originalimage? Originalimage { get; set; }
#nullable restore
#else
        public global::Soenneker.Wikimedia.OpenApiClient.Models.Originalimage Originalimage { get; set; }
#endif
        /// <summary>The page ID</summary>
        public int? Pageid { get; set; }
        /// <summary>The thumbnail property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Wikimedia.OpenApiClient.Models.Thumbnail? Thumbnail { get; set; }
#nullable restore
#else
        public global::Soenneker.Wikimedia.OpenApiClient.Models.Thumbnail Thumbnail { get; set; }
#endif
        /// <summary>The time when the page was last edited in the [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Timestamp { get; set; }
#nullable restore
#else
        public string Timestamp { get; set; }
#endif
        /// <summary>&quot;The page title.Deprecated: Use `titles.normalized` instead.&quot;</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>a good example of the differences can be seen in https://en.wikipedia.org/api/rest_v1/page/summary/IOS_13</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Wikimedia.OpenApiClient.Models.Titles_set? Titles { get; set; }
#nullable restore
#else
        public global::Soenneker.Wikimedia.OpenApiClient.Models.Titles_set Titles { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wikimedia.OpenApiClient.Models.Summary"/> and sets the default values.
        /// </summary>
        public Summary()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wikimedia.OpenApiClient.Models.Summary"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Wikimedia.OpenApiClient.Models.Summary CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Wikimedia.OpenApiClient.Models.Summary();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "coordinates", n => { Coordinates = n.GetObjectValue<global::Soenneker.Wikimedia.OpenApiClient.Models.Summary_coordinates>(global::Soenneker.Wikimedia.OpenApiClient.Models.Summary_coordinates.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "dir", n => { Dir = n.GetStringValue(); } },
                { "displaytitle", n => { Displaytitle = n.GetStringValue(); } },
                { "extract", n => { Extract = n.GetStringValue(); } },
                { "extract_html", n => { ExtractHtml = n.GetStringValue(); } },
                { "lang", n => { Lang = n.GetStringValue(); } },
                { "originalimage", n => { Originalimage = n.GetObjectValue<global::Soenneker.Wikimedia.OpenApiClient.Models.Originalimage>(global::Soenneker.Wikimedia.OpenApiClient.Models.Originalimage.CreateFromDiscriminatorValue); } },
                { "pageid", n => { Pageid = n.GetIntValue(); } },
                { "thumbnail", n => { Thumbnail = n.GetObjectValue<global::Soenneker.Wikimedia.OpenApiClient.Models.Thumbnail>(global::Soenneker.Wikimedia.OpenApiClient.Models.Thumbnail.CreateFromDiscriminatorValue); } },
                { "timestamp", n => { Timestamp = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "titles", n => { Titles = n.GetObjectValue<global::Soenneker.Wikimedia.OpenApiClient.Models.Titles_set>(global::Soenneker.Wikimedia.OpenApiClient.Models.Titles_set.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Wikimedia.OpenApiClient.Models.Summary_coordinates>("coordinates", Coordinates);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("dir", Dir);
            writer.WriteStringValue("displaytitle", Displaytitle);
            writer.WriteStringValue("extract", Extract);
            writer.WriteStringValue("extract_html", ExtractHtml);
            writer.WriteStringValue("lang", Lang);
            writer.WriteObjectValue<global::Soenneker.Wikimedia.OpenApiClient.Models.Originalimage>("originalimage", Originalimage);
            writer.WriteIntValue("pageid", Pageid);
            writer.WriteObjectValue<global::Soenneker.Wikimedia.OpenApiClient.Models.Thumbnail>("thumbnail", Thumbnail);
            writer.WriteStringValue("timestamp", Timestamp);
            writer.WriteStringValue("title", Title);
            writer.WriteObjectValue<global::Soenneker.Wikimedia.OpenApiClient.Models.Titles_set>("titles", Titles);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
