// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Wikimedia.OpenApiClient.Transform.Html;
using Soenneker.Wikimedia.OpenApiClient.Transform.Wikitext;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Wikimedia.OpenApiClient.Transform
{
    /// <summary>
    /// Builds and executes requests for operations under \transform
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TransformRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The html property</summary>
        public global::Soenneker.Wikimedia.OpenApiClient.Transform.Html.HtmlRequestBuilder Html
        {
            get => new global::Soenneker.Wikimedia.OpenApiClient.Transform.Html.HtmlRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The wikitext property</summary>
        public global::Soenneker.Wikimedia.OpenApiClient.Transform.Wikitext.WikitextRequestBuilder Wikitext
        {
            get => new global::Soenneker.Wikimedia.OpenApiClient.Transform.Wikitext.WikitextRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wikimedia.OpenApiClient.Transform.TransformRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TransformRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/transform", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wikimedia.OpenApiClient.Transform.TransformRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TransformRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/transform", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
