// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Wikimedia.OpenApiClient.Data.Citation.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Wikimedia.OpenApiClient.Data.Citation
{
    /// <summary>
    /// Builds and executes requests for operations under \data\citation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CitationRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Wikimedia.OpenApiClient.data.citation.item collection</summary>
        /// <param name="position">The format to use for the resulting citation data</param>
        /// <returns>A <see cref="global::Soenneker.Wikimedia.OpenApiClient.Data.Citation.Item.WithFormatItemRequestBuilder"/></returns>
        public global::Soenneker.Wikimedia.OpenApiClient.Data.Citation.Item.WithFormatItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("format", position);
                return new global::Soenneker.Wikimedia.OpenApiClient.Data.Citation.Item.WithFormatItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wikimedia.OpenApiClient.Data.Citation.CitationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CitationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/data/citation", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wikimedia.OpenApiClient.Data.Citation.CitationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CitationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/data/citation", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
