// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Wikimedia.OpenApiClient.Media.MathNamespace.Render.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Wikimedia.OpenApiClient.Media.MathNamespace.Render
{
    /// <summary>
    /// Builds and executes requests for operations under \media\math\render
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RenderRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Wikimedia.OpenApiClient.media.math.render.item collection</summary>
        /// <param name="position">The output format; can be svg or mml</param>
        /// <returns>A <see cref="global::Soenneker.Wikimedia.OpenApiClient.Media.MathNamespace.Render.Item.WithFormatItemRequestBuilder"/></returns>
        public global::Soenneker.Wikimedia.OpenApiClient.Media.MathNamespace.Render.Item.WithFormatItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("format", position);
                return new global::Soenneker.Wikimedia.OpenApiClient.Media.MathNamespace.Render.Item.WithFormatItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wikimedia.OpenApiClient.Media.MathNamespace.Render.RenderRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RenderRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/media/math/render", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wikimedia.OpenApiClient.Media.MathNamespace.Render.RenderRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RenderRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/media/math/render", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
