// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Wikimedia.OpenApiClient.Data.Css.Mobile.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Wikimedia.OpenApiClient.Data.Css.Mobile
{
    /// <summary>
    /// Builds and executes requests for operations under \data\css\mobile
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MobileRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Wikimedia.OpenApiClient.data.css.mobile.item collection</summary>
        /// <param name="position">The desired CSS bundle</param>
        /// <returns>A <see cref="global::Soenneker.Wikimedia.OpenApiClient.Data.Css.Mobile.Item.WithTypeItemRequestBuilder"/></returns>
        public global::Soenneker.Wikimedia.OpenApiClient.Data.Css.Mobile.Item.WithTypeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("type", position);
                return new global::Soenneker.Wikimedia.OpenApiClient.Data.Css.Mobile.Item.WithTypeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wikimedia.OpenApiClient.Data.Css.Mobile.MobileRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MobileRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/data/css/mobile", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wikimedia.OpenApiClient.Data.Css.Mobile.MobileRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MobileRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/data/css/mobile", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
