// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Wikimedia.OpenApiClient.Media.MathNamespace.Check;
using Soenneker.Wikimedia.OpenApiClient.Media.MathNamespace.Formula;
using Soenneker.Wikimedia.OpenApiClient.Media.MathNamespace.Render;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Wikimedia.OpenApiClient.Media.MathNamespace
{
    /// <summary>
    /// Builds and executes requests for operations under \media\math
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MathRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The check property</summary>
        public global::Soenneker.Wikimedia.OpenApiClient.Media.MathNamespace.Check.CheckRequestBuilder Check
        {
            get => new global::Soenneker.Wikimedia.OpenApiClient.Media.MathNamespace.Check.CheckRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The formula property</summary>
        public global::Soenneker.Wikimedia.OpenApiClient.Media.MathNamespace.Formula.FormulaRequestBuilder Formula
        {
            get => new global::Soenneker.Wikimedia.OpenApiClient.Media.MathNamespace.Formula.FormulaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The render property</summary>
        public global::Soenneker.Wikimedia.OpenApiClient.Media.MathNamespace.Render.RenderRequestBuilder Render
        {
            get => new global::Soenneker.Wikimedia.OpenApiClient.Media.MathNamespace.Render.RenderRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wikimedia.OpenApiClient.Media.MathNamespace.MathRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MathRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/media/math", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wikimedia.OpenApiClient.Media.MathNamespace.MathRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MathRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/media/math", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
