// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Wikimedia.OpenApiClient.Models;
using Soenneker.Wikimedia.OpenApiClient.Page.Html;
using Soenneker.Wikimedia.OpenApiClient.Page.Lint;
using Soenneker.Wikimedia.OpenApiClient.Page.MediaList;
using Soenneker.Wikimedia.OpenApiClient.Page.MobileHtml;
using Soenneker.Wikimedia.OpenApiClient.Page.MobileHtmlOfflineResources;
using Soenneker.Wikimedia.OpenApiClient.Page.Summary;
using Soenneker.Wikimedia.OpenApiClient.Page.Talk;
using Soenneker.Wikimedia.OpenApiClient.Page.Title;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Wikimedia.OpenApiClient.Page
{
    /// <summary>
    /// Builds and executes requests for operations under \page
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PageRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The html property</summary>
        public global::Soenneker.Wikimedia.OpenApiClient.Page.Html.HtmlRequestBuilder Html
        {
            get => new global::Soenneker.Wikimedia.OpenApiClient.Page.Html.HtmlRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The lint property</summary>
        public global::Soenneker.Wikimedia.OpenApiClient.Page.Lint.LintRequestBuilder Lint
        {
            get => new global::Soenneker.Wikimedia.OpenApiClient.Page.Lint.LintRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mediaList property</summary>
        public global::Soenneker.Wikimedia.OpenApiClient.Page.MediaList.MediaListRequestBuilder MediaList
        {
            get => new global::Soenneker.Wikimedia.OpenApiClient.Page.MediaList.MediaListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mobileHtml property</summary>
        public global::Soenneker.Wikimedia.OpenApiClient.Page.MobileHtml.MobileHtmlRequestBuilder MobileHtml
        {
            get => new global::Soenneker.Wikimedia.OpenApiClient.Page.MobileHtml.MobileHtmlRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mobileHtmlOfflineResources property</summary>
        public global::Soenneker.Wikimedia.OpenApiClient.Page.MobileHtmlOfflineResources.MobileHtmlOfflineResourcesRequestBuilder MobileHtmlOfflineResources
        {
            get => new global::Soenneker.Wikimedia.OpenApiClient.Page.MobileHtmlOfflineResources.MobileHtmlOfflineResourcesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The summary property</summary>
        public global::Soenneker.Wikimedia.OpenApiClient.Page.Summary.SummaryRequestBuilder Summary
        {
            get => new global::Soenneker.Wikimedia.OpenApiClient.Page.Summary.SummaryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The talk property</summary>
        public global::Soenneker.Wikimedia.OpenApiClient.Page.Talk.TalkRequestBuilder Talk
        {
            get => new global::Soenneker.Wikimedia.OpenApiClient.Page.Talk.TalkRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The title property</summary>
        public global::Soenneker.Wikimedia.OpenApiClient.Page.Title.TitleRequestBuilder Title
        {
            get => new global::Soenneker.Wikimedia.OpenApiClient.Page.Title.TitleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wikimedia.OpenApiClient.Page.PageRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PageRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/page", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wikimedia.OpenApiClient.Page.PageRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PageRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/page", rawUrl)
        {
        }
        /// <summary>
        /// &quot;Stability: [stable](https://www.mediawiki.org/wiki/API_versioning#Stable)&quot;
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wikimedia.OpenApiClient.Models.Listing"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Wikimedia.OpenApiClient.Models.Problem">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Wikimedia.OpenApiClient.Models.Listing?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Wikimedia.OpenApiClient.Models.Listing> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Wikimedia.OpenApiClient.Models.Problem.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Wikimedia.OpenApiClient.Models.Listing>(requestInfo, global::Soenneker.Wikimedia.OpenApiClient.Models.Listing.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &quot;Stability: [stable](https://www.mediawiki.org/wiki/API_versioning#Stable)&quot;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wikimedia.OpenApiClient.Page.PageRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Wikimedia.OpenApiClient.Page.PageRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Wikimedia.OpenApiClient.Page.PageRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
