// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Wikimedia.OpenApiClient.Data.Recommendation.Article.Creation.Translation.Item.Item;
using Soenneker.Wikimedia.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Wikimedia.OpenApiClient.Data.Recommendation.Article.Creation.Translation.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \data\recommendation\article\creation\translation\{from_lang}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithFrom_langItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Wikimedia.OpenApiClient.data.recommendation.article.creation.translation.item.item collection</summary>
        /// <param name="position">The article to use as a search seed</param>
        /// <returns>A <see cref="global::Soenneker.Wikimedia.OpenApiClient.Data.Recommendation.Article.Creation.Translation.Item.Item.WithSeed_articleItemRequestBuilder"/></returns>
        public global::Soenneker.Wikimedia.OpenApiClient.Data.Recommendation.Article.Creation.Translation.Item.Item.WithSeed_articleItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("seed_article", position);
                return new global::Soenneker.Wikimedia.OpenApiClient.Data.Recommendation.Article.Creation.Translation.Item.Item.WithSeed_articleItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wikimedia.OpenApiClient.Data.Recommendation.Article.Creation.Translation.Item.WithFrom_langItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithFrom_langItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/data/recommendation/article/creation/translation/{from_lang}{?count*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wikimedia.OpenApiClient.Data.Recommendation.Article.Creation.Translation.Item.WithFrom_langItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithFrom_langItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/data/recommendation/article/creation/translation/{from_lang}{?count*}", rawUrl)
        {
        }
        /// <summary>
        /// &quot;Recommends articles to be translated from the sourceto the domain language.See more at [Recommendation API documentation](https://meta.wikimedia.org/wiki/Recommendation_API)Stability: [unstable](https://www.mediawiki.org/wiki/API_versioning#Unstable)&quot;
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wikimedia.OpenApiClient.Models.Recommendation_result"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Wikimedia.OpenApiClient.Models.Problem">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Wikimedia.OpenApiClient.Models.Recommendation_result?> GetAsync(Action<RequestConfiguration<global::Soenneker.Wikimedia.OpenApiClient.Data.Recommendation.Article.Creation.Translation.Item.WithFrom_langItemRequestBuilder.WithFrom_langItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Wikimedia.OpenApiClient.Models.Recommendation_result> GetAsync(Action<RequestConfiguration<global::Soenneker.Wikimedia.OpenApiClient.Data.Recommendation.Article.Creation.Translation.Item.WithFrom_langItemRequestBuilder.WithFrom_langItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Wikimedia.OpenApiClient.Models.Problem.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Wikimedia.OpenApiClient.Models.Recommendation_result>(requestInfo, global::Soenneker.Wikimedia.OpenApiClient.Models.Recommendation_result.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &quot;Recommends articles to be translated from the sourceto the domain language.See more at [Recommendation API documentation](https://meta.wikimedia.org/wiki/Recommendation_API)Stability: [unstable](https://www.mediawiki.org/wiki/API_versioning#Unstable)&quot;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Wikimedia.OpenApiClient.Data.Recommendation.Article.Creation.Translation.Item.WithFrom_langItemRequestBuilder.WithFrom_langItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Wikimedia.OpenApiClient.Data.Recommendation.Article.Creation.Translation.Item.WithFrom_langItemRequestBuilder.WithFrom_langItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wikimedia.OpenApiClient.Data.Recommendation.Article.Creation.Translation.Item.WithFrom_langItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Wikimedia.OpenApiClient.Data.Recommendation.Article.Creation.Translation.Item.WithFrom_langItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Wikimedia.OpenApiClient.Data.Recommendation.Article.Creation.Translation.Item.WithFrom_langItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// &quot;Recommends articles to be translated from the sourceto the domain language.See more at [Recommendation API documentation](https://meta.wikimedia.org/wiki/Recommendation_API)Stability: [unstable](https://www.mediawiki.org/wiki/API_versioning#Unstable)&quot;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithFrom_langItemRequestBuilderGetQueryParameters 
        {
            /// <summary>The max number of articles to return</summary>
            [QueryParameter("count")]
            public int? Count { get; set; }
        }
    }
}
#pragma warning restore CS0618
